# Generated by Django 5.2.9 on 2025-12-29 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('DestinationGuide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.destinationguide')),
                ('Festivals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.festivals')),
                ('activites', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.activities')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.country')),
                ('countryinfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.countryinfo')),
                ('famousphotopoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.famousphotopoint')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.hotel')),
                ('mainattraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.mainattraction')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.market')),
                ('placeinformation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.placeinformation')),
                ('placesToEat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.placestoeat')),
                ('placestovisit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.placestovisit')),
                ('specialZone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.specialzone')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.state')),
                ('thingsToDo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.thingstodo')),
                ('travelhacks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.travelhacks')),
            ],
        ),
    ]
