# Generated by Django 5.2.9 on 2025-12-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='header_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
