# Generated by Django 5.2.9 on 2025-12-31 06:47

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_hotel_header_image_hotel_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='pin',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='activities',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rating out of 5', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='countryinfo',
            name='pin',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='countryinfo',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rating out of 5', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='destinationguide',
            name='pin',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='destinationguide',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rating out of 5', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='famousphotopoint',
            name='pin',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='famousphotopoint',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rating out of 5', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='festivals',
            name='pin',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='festivals',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rating out of 5', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='pin',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rating out of 5', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='mainattraction',
            name='pin',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='mainattraction',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rating out of 5', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='market',
            name='pin',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='market',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rating out of 5', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='placeinformation',
            name='pin',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='placeinformation',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rating out of 5', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='placestoeat',
            name='pin',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='placestoeat',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rating out of 5', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='placestovisit',
            name='pin',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='placestovisit',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rating out of 5', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='thingstodo',
            name='pin',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='thingstodo',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rating out of 5', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='travelhacks',
            name='pin',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='travelhacks',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rating out of 5', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
