# Generated by Django 5.2.9 on 2026-01-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0004_activities_created_by_countryinfo_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='marker_icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='countryinfo',
            name='marker_icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='destinationguide',
            name='marker_icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='famousphotopoint',
            name='marker_icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='festivals',
            name='marker_icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='marker_icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mainattraction',
            name='marker_icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='market',
            name='marker_icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='placeinformation',
            name='marker_icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='placestoeat',
            name='marker_icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='placestovisit',
            name='marker_icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='thingstodo',
            name='marker_icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='travelhacks',
            name='marker_icon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
