# Generated by Django 5.2.9 on 2025-12-29 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTACategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'cta_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CTAButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('btncolor', models.CharField(blank=True, help_text='Button color (hex, name, or theme key)', max_length=50)),
                ('url', models.URLField()),
                ('btn_ranking', models.IntegerField(default=0, help_text='Order of button within same pin')),
                ('cat_ranking', models.IntegerField(default=0, help_text='Order of category grouping')),
                ('btn_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='M', max_length=5)),
                ('published', models.BooleanField(default=True)),
                ('activites', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.activities')),
                ('countryinfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.countryinfo')),
                ('destinationguide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.destinationguide')),
                ('famousphotopoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.famousphotopoint')),
                ('festival', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.festivals')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.hotel')),
                ('mainattraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.mainattraction')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.market')),
                ('placeinformation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.placeinformation')),
                ('placestoeat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.placestoeat')),
                ('placestovisit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.placestovisit')),
                ('thingstodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.thingstodo')),
                ('travelhacks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.travelhacks')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direction.ctacategory')),
            ],
            options={
                'db_table': 'cta_buttons',
                'ordering': ['cat_ranking', 'btn_ranking'],
            },
        ),
    ]
