# Generated by Django 5.2.9 on 2025-12-29 05:18

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('pins', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('website', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'post_platforms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('DestinationGuide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.destinationguide')),
                ('Festivals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.festivals')),
                ('activites', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.activities')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.country')),
                ('countryinfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.countryinfo')),
                ('famousphotopoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.famousphotopoint')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.hotel')),
                ('mainattraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.mainattraction')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.market')),
                ('placeinformation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.placeinformation')),
                ('placesToEat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.placestoeat')),
                ('placestovisit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.placestovisit')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='social.postplatform')),
                ('specialzone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.specialzone')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.state')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('thingsToDo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.thingstodo')),
                ('travelhacks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.travelhacks')),
            ],
            options={
                'db_table': 'social_posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
