# Generated by Django 5.2.9 on 2026-01-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
